name: release_docker

on:
  push:
    tags:
      - '*'

jobs:
  release_docker:
    name: Release Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: wulaguy/alist

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: wulaguy
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
